(() => {
  'use strict';
  const VERSION='0.4.1-beta.23', FLAG='__answerMeCompactUiV23', UI_ID='answer_me_compact_ui_v23', STYLE_ID='answer_me_compact_ui_style_v23';
  if(window[FLAG]) return; window[FLAG]=true;
  const ctx=()=>window.SillyTavern?.getContext?.()??null;
  const router=()=>window.AnswerMeModelRouter??null;
  const selector=()=>window.AnswerMeSiteSelector??null;
  const profiles=()=>Array.isArray(ctx()?.extensionSettings?.connectionManager?.profiles)?ctx().extensionSettings.connectionManager.profiles:[];
  const profile=id=>profiles().find(p=>String(p?.id)===String(id));
  const settings=()=>{const c=ctx();if(!c)return null;c.extensionSettings.answerMe??={};const s=c.extensionSettings.answerMe;if(typeof s.compactSitesOpen!=='boolean')s.compactSitesOpen=false;if(typeof s.compactAdvancedOpen!=='boolean')s.compactAdvancedOpen=false;if(typeof s.keywordManualOpen!=='boolean')s.keywordManualOpen=false;return s};
  const save=()=>{try{ctx()?.saveSettingsDebounced?.()}catch{}};
  let refs=null, timer=null, observer=null;

  function styles(){if(document.getElementById(STYLE_ID))return;const st=document.createElement('style');st.id=STYLE_ID;st.textContent=`
    #answer_me_compact_ui_v19,#answer_me_compact_ui_v20,#answer_me_site_selector_v16,#answer_me_model_router_v14{display:none!important}
    #${UI_ID}{margin:10px 0 12px;padding:11px;border:1px solid var(--SmartThemeBorderColor,rgba(255,255,255,.12));border-radius:14px;background:linear-gradient(145deg,rgba(127,127,127,.075),rgba(127,127,127,.035));box-shadow:0 5px 18px rgba(0,0,0,.04)}
    #${UI_ID} .top{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-bottom:9px}.main{font-weight:800}.badge{font-size:.75em;opacity:.68;padding:2px 7px;border-radius:999px;background:rgba(127,127,127,.1)}
    #${UI_ID} .grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.field{display:grid;gap:4px}.field>span{font-size:.72em;opacity:.64;font-weight:700}
    #${UI_ID} select{width:100%;height:34px;padding:4px 28px 4px 9px;border-radius:9px;border:1px solid var(--SmartThemeBorderColor,rgba(255,255,255,.14));background:rgba(127,127,127,.06);color:inherit}
    #${UI_ID} .modes{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}#${UI_ID} button{color:inherit;cursor:pointer}#${UI_ID} .modes button,#${UI_ID} .mini{border:1px solid var(--SmartThemeBorderColor,rgba(255,255,255,.14));background:rgba(127,127,127,.055);border-radius:9px;padding:7px 8px}.modes .on{font-weight:800;background:rgba(127,127,127,.19)}
    #${UI_ID} .section{margin-top:9px;padding-top:9px;border-top:1px solid var(--SmartThemeBorderColor,rgba(255,255,255,.09))}.head{display:flex;justify-content:space-between;gap:8px;cursor:pointer}.title{font-size:.85em;font-weight:750}.meta{font-size:.76em;opacity:.62}
    #${UI_ID} .sites{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-top:8px}.site{min-width:0;text-align:left;border:1px solid var(--SmartThemeBorderColor,rgba(255,255,255,.12));background:rgba(127,127,127,.045);border-radius:9px;padding:7px 8px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.site.on{font-weight:750;background:rgba(127,127,127,.15)}.site.off{opacity:.42}.links{display:flex;gap:12px;margin-top:7px}.link{border:0;background:transparent;padding:0;font-size:.78em;opacity:.7}.advanced{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.note{font-size:.75em;opacity:.58;margin-top:7px;word-break:break-word}
    #${UI_ID}.manual-open + #answer_me_model_router_v14{display:block!important;margin-top:8px!important;padding:8px!important;background:rgba(127,127,127,.035)!important}#${UI_ID}.manual-open + #answer_me_model_router_v14>:not(.am18-manual){display:none!important}#${UI_ID}.manual-open + #answer_me_model_router_v14 .am18-manual{display:block!important;margin-top:0!important;padding-top:0!important;border-top:0!important}
    @media(max-width:700px){#${UI_ID}{padding:10px}}
  `;document.head.appendChild(st)}

  function anchor(){const root=document.querySelector('#answer_me_settings');const old=root?.querySelector('#answer_me_model_router_v14');const a=root?.querySelector('.answer-me-note')||root?.querySelector('.answer-me-head');if(!root||!old||!a)return null;let box=root.querySelector('#'+UI_ID);if(!box){box=document.createElement('div');box.id=UI_ID;a.insertAdjacentElement('afterend',box);box.innerHTML=`<div class="top"><span class="main"></span><span class="badge modeBadge"></span><span class="badge siteBadge"></span></div><div class="grid"><label class="field"><span>模型系列</span><select class="family"></select></label><label class="field"><span>版本</span><select class="version"></select></label></div><div class="modes"><button data-mode="stream">🟢 真流式</button><button data-mode="fake">📦 假流式</button></div><div class="section"><div class="head sitesHead"><span class="title sitesTitle"></span><span class="meta sitesMeta"></span></div><div class="sitesBody"><div class="sites"></div><div class="links"><button class="link all">全选可用站</button><button class="link one">只留当前站</button></div></div></div><div class="section"><div class="head advHead"><span class="title advTitle"></span><span class="meta advMeta"></span></div><div class="advBody"><div class="advanced"><button class="mini scan">↻ 重扫模型</button><button class="mini manual">✎ 手动校正识别</button></div><div class="note"></div></div></div>`}
    if(a.nextElementSibling!==box)a.insertAdjacentElement('afterend',box);if(box.nextElementSibling!==old)box.insertAdjacentElement('afterend',old);return box}

  function families(){const r=router(),s=settings(),mode=r?.transportMode||'stream',map=new Map();if(!r?.classify||!s)return[];for(const p of profiles()){const m=[...(s.modelCatalog?.[p.id]?.models||[]),p.model].filter(Boolean);for(const model of new Set(m.map(String))){let i;try{i=r.classify(p.id,model)}catch{continue}if(!i||i.ignored||i.transport!==mode||!i.family)continue;if(!map.has(i.family))map.set(i.family,new Set());map.get(i.family).add(String(p.id))}}return[...map].map(([name,ids])=>({name,count:ids.size})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name))}
  function setOptions(el,items,value,label){const sig=JSON.stringify(items.map(x=>[x.value,x.text]));if(el.dataset.sig!==sig){el.dataset.sig=sig;el.replaceChildren(...items.map(x=>{const o=document.createElement('option');o.value=x.value;o.textContent=x.text;return o}))}if(el.value!==value)el.value=value;el.disabled=!items.length;if(!items.length){const o=document.createElement('option');o.textContent=label;el.appendChild(o)}}
  function bind(box){if(box.dataset.bound)return;box.dataset.bound='1';box.querySelector('.family').onchange=async e=>{e.currentTarget.disabled=true;try{await router()?.setFamily?.(e.currentTarget.value)}finally{update()}};box.querySelector('.version').onchange=async e=>{e.currentTarget.disabled=true;try{await router()?.select?.(e.currentTarget.value)}finally{update()}};box.querySelectorAll('.modes button').forEach(b=>b.onclick=async()=>{if(b.dataset.mode===router()?.transportMode)return;b.disabled=true;try{await router()?.setTransport?.(b.dataset.mode)}finally{update()}});box.querySelector('.sitesHead').onclick=()=>{const s=settings();s.compactSitesOpen=!s.compactSitesOpen;save();update()};box.querySelector('.advHead').onclick=()=>{const s=settings();s.compactAdvancedOpen=!s.compactAdvancedOpen;save();update()};box.querySelector('.all').onclick=async()=>{await selector()?.selectAll?.();update()};box.querySelector('.one').onclick=async()=>{await selector()?.onlyCurrent?.();update()};box.querySelector('.scan').onclick=async()=>{await router()?.scan?.(true);update()};box.querySelector('.manual').onclick=()=>{const s=settings(),next=!s.keywordManualOpen,old=document.querySelector('#answer_me_model_router_v14'),btn=[...(old?.querySelectorAll('.am18-action')||[])].find(x=>String(x.textContent).includes('手动校正'));if(btn)btn.click();s.keywordManualOpen=next;save();update()}}
  function siteButtons(box,eligible,selected){const wrap=box.querySelector('.sites'),sig=JSON.stringify([eligible,[...selected]]);if(wrap.dataset.sig===sig)return;wrap.dataset.sig=sig;wrap.replaceChildren();for(const id of eligible){const p=profile(id);if(!p)continue;const on=selected.has(String(id)),b=document.createElement('button');b.className=`site ${on?'on':'off'}`;b.textContent=`${on?'✓':'○'} ${p.name||'未命名站'}`;b.onclick=async()=>{b.disabled=true;try{await selector()?.toggle?.(id)}finally{update()}};wrap.appendChild(b)}}
  function update(){const box=anchor(),r=router(),sel=selector(),s=settings();if(!box||!r||!sel||!s)return;styles();bind(box);const g=r.selected,mode=r.transportMode||'stream',fam=r.family||g?.family||'',fl=families(),vl=Array.isArray(r.groups?.())?r.groups():[],eligible=Array.isArray(sel.eligibleIds)?sel.eligibleIds.map(String):[],selected=new Set((Array.isArray(sel.selectedIds)?sel.selectedIds:[]).map(String));box.querySelector('.main').textContent=g?`${g.family} ${g.version}`:(fam||'未选模型');box.querySelector('.modeBadge').textContent=mode==='stream'?'🟢 真流':'📦 假流';box.querySelector('.siteBadge').textContent=`${selected.size}/${eligible.length} 家`;setOptions(box.querySelector('.family'),fl.map(x=>({value:x.name,text:`${x.name} · ${x.count}`})),fam,'暂无系列');setOptions(box.querySelector('.version'),vl.map(x=>({value:x.key,text:`${x.version} · ${x.profileCount}家`})),g?.key||'','暂无版本');box.querySelectorAll('.modes button').forEach(b=>{b.classList.toggle('on',b.dataset.mode===mode);b.disabled=false});box.querySelector('.sitesTitle').textContent=`${s.compactSitesOpen?'▾':'▸'} 参赛站`;box.querySelector('.sitesMeta').textContent=`${selected.size}/${eligible.length} 家`;box.querySelector('.sitesBody').style.display=s.compactSitesOpen?'block':'none';if(s.compactSitesOpen)siteButtons(box,eligible,selected);box.querySelector('.advTitle').textContent=`${s.compactAdvancedOpen?'▾':'▸'} 高级设置`;const total=profiles().length,full=profiles().filter(p=>s.modelCatalog?.[p.id]?.fallback===false).length;box.querySelector('.advMeta').textContent=`${full}/${total} 家已扫描`;box.querySelector('.advBody').style.display=s.compactAdvancedOpen?'block':'none';box.querySelector('.manual').textContent=s.keywordManualOpen?'收起手动校正':'✎ 手动校正识别';box.querySelector('.note').textContent=g?.keyword?`当前关键模型名：${g.keyword}`:'';box.classList.toggle('manual-open',!!s.keywordManualOpen)}
  function schedule(){clearTimeout(timer);timer=setTimeout(update,40)}
  async function boot(){for(let i=0;i<140;i++){if(ctx()&&router()?.groups&&selector()&&document.querySelector('#answer_me_settings'))break;await new Promise(r=>setTimeout(r,100))}styles();update();const root=document.querySelector('#answer_me_settings');observer=new MutationObserver(schedule);if(root)observer.observe(root,{childList:true,subtree:true});setInterval(update,1200);console.log(`[💢 Answer Me] compact UI ${VERSION} ready · no forced scroll restoration`)}
  boot().catch(e=>console.error('[💢 Answer Me] compact UI v23 failed',e));
})();
